export const MAIN_FORM_VALUES_KEYS = [
  'title',
  'slug',
  'category',
  'level',
  // image_id: course.image?.id,
  'duration_info',
  'video_duration',
  // co_instructor_id: course.co_instructor?.id,
  'content',
  'excerpt',
  'status',
  'status_date_start',
  'status_date_end',
  'views',
  'students_limit',
  'current_students',
  'is_featured',
  'access_duration',
  'access_devices',
  'certificate_info',
];
